export const popularKeywords: string[] = [
  // Core intents
  "create images",
  "image generation",
  "edit photos",
  "remove backgrounds",
  "upscale images",
  "restore images",
  "design logos",
  "make videos",
  "video generation",
  "video editing",
  "avatar videos",
  "presentations",
  "slides",
  "write content",
  "blog posts",
  "essays",
  "write emails",
  "summarize",
  "translate",
  "brainstorm",
  "research",
  "answer engine",
  "citations",
  "chat with pdf",
  "data analysis",
  "spreadsheets",
  "automate tasks",
  "workflows",
  "seo",
  "marketing",
  "social media posts",
  "ad copy",
  "product descriptions",
  "brand voice",
  "storyboards",
  "copywriting",
  "transcription",
  "speech to text",
  "text to speech",
  "ai voice",
  "voice cloning",
  "podcast editing",
  "music",
  "sound effects",
  "code assistant",
  "generate code",
  "code autocomplete",
  "debugging",
  "documentation",
  "unit tests",
  "diagramming",
  "ui design",
  "prototyping",
  "wireframes",
  "whiteboarding",
  "knowledge base",
  "meeting notes",
  "note taking",
  "pdf summary",
  "web scraping",
  "customer support",
  "chatbots",
  "Q&A",
  "long context",
  "multimodal",
  "image understanding",
  "vision",
  "reasoning",
  "math",
  // Additional long-tail/search-friendly variations
  "generate logos",
  "logo maker",
  "thumbnail maker",
  "remove objects",
  "background remover",
  "color grading",
  "video to video",
  "text to video",
  "image to video",
  "b-roll",
  "shorts",
  "tiktok videos",
  "youtube scripts",
  "linkedin posts",
  "twitter posts",
  "newsletters",
  "landing pages",
  "product pages",
  "press releases",
  "meta descriptions",
  "blog outlines",
  "rewrite",
  "paraphrase",
  "grammar",
  "tone change",
  "summarize meetings",
  "action items",
  "knowledge graph",
  "excel formulas",
  "powerpoint",
  "word documents",
  "google docs",
  "google sheets",
  "google slides",
  "brand kit",
  "style transfer",
  "concept art",
  "game assets",
  "textures",
  "icons",
  "illustrations",
  "photorealistic images",
  "headshots",
  "avatars",
  "face swap",
  "voiceover",
  "dubbing",
  "localization",
  "knowledge citations",
  "source links",
  "web search",
  "browsing",
];
