import type { ToolItem } from "@/types/tools";

export const tools: ToolItem[] = [
  {
    id: "chatgpt",
    name: "ChatGPT",
    tagline: "Conversational AI for writing, brainstorming, and problem-solving",
    rating: 4.8,
    difficulty: "Easy",
    price: "$ Free + $20/month",
    prosCons: {
      pros: ["Versatile", "Great for beginners", "Strong reasoning"],
      cons: ["Can be verbose", "Knowledge cutoff"],
    },
    ctaLabel: "Try ChatGPT",
  ctaHref: "https://chat.openai.com",
  logo: "/images/chatgpt.svg",
  categories: ["Chat", "Writing", "Research", "Coding"],
  tags: ["Generalist", "OpenAI", "GPT"],
    keywords: [
      "write content",
      "brainstorm",
      "summarize",
      "translate",
      "research",
      "reasoning",
      "math",
      "code assistant",
      "chatbots",
      "customer support",
      "knowledge base",
    ],
  },
  {
    id: "midjourney",
    name: "Midjourney",
    tagline: "AI image generator for stunning artwork and visuals",
    rating: 4.7,
    difficulty: "Medium",
    price: "$ 10–60/month",
    prosCons: {
      pros: ["Highest quality images", "Active community", "Unique artistic style"],
      cons: ["Discord-based", "Learning curve", "No free tier"],
    },
    ctaLabel: "Try Midjourney",
  ctaHref: "https://www.midjourney.com",
  logo: "/images/midjourney.svg",
  categories: ["Images", "Design"],
  tags: ["Art", "Generative"],
    keywords: [
      "create images",
      "image generation",
      "concept art",
      "illustrations",
      "photorealistic images",
      "logos",
      "thumbnails",
    ],
  },
  {
    id: "claude",
    name: "Claude",
    tagline: "Helpful, honest, and harmless assistant for reasoning and writing",
    rating: 4.8,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Great long-context", "Strong writing", "Safe outputs"],
      cons: ["Occasional refusals", "Web access varies"],
    },
  ctaLabel: "Try Claude",
  ctaHref: "https://claude.ai",
  logo: "/images/claude.svg",
  categories: ["Chat", "Writing", "Research"],
  tags: ["Long context", "Anthropic"],
    keywords: [
      "write content",
      "long context",
      "reasoning",
      "summarize",
      "research",
      "brainstorm",
      "knowledge base",
    ],
  },
  {
    id: "gemini",
    name: "Google Gemini",
    tagline: "Multimodal AI for text, images, and code with Google integration",
    rating: 4.6,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Strong search integration", "Multimodal", "Great for Google users"],
      cons: ["Inconsistent coding", "Occasional guardrails"],
    },
  ctaLabel: "Try Gemini",
  ctaHref: "https://gemini.google.com",
  logo: "/images/gemini.svg",
  categories: ["Chat", "Multimodal", "Coding"],
  tags: ["Google"],
    keywords: [
      "multimodal",
      "image understanding",
      "vision",
      "web search",
      "browsing",
      "write content",
  "workspace",
  "gmail",
  "google docs",
    ],
  },
  {
    id: "perplexity",
    name: "Perplexity",
    tagline: "Answer engine with citations and focused research workflows",
    rating: 4.7,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Fast with sources", "Great browsing", "Good follow-ups"],
      cons: ["Limited creativity", "Pro features gated"],
    },
    ctaLabel: "Try Perplexity",
  ctaHref: "https://www.perplexity.ai",
  logo: "/images/perplexity.svg",
  categories: ["Research", "Search"],
  tags: ["Citations", "Answer engine"],
  keywords: ["research", "answer engine", "citations", "web search", "browsing"],
  },
  {
    id: "copilot",
    name: "GitHub Copilot",
    tagline: "AI pair programmer for code suggestions and completions",
    rating: 4.6,
    difficulty: "Easy",
    price: "$ 10–19/user/month",
    prosCons: {
      pros: ["Boosts productivity", "Great editor integration", "Strong autocomplete"],
      cons: ["Hallucinated APIs", "Not a substitute for tests"],
    },
    ctaLabel: "Try GitHub Copilot",
  ctaHref: "https://github.com/features/copilot",
  logo: "/images/copilot.svg",
  categories: ["Coding"],
  tags: ["Autocomplete", "Pair programming"],
  keywords: ["code assistant", "generate code", "code autocomplete", "unit tests"],
  },
  {
    id: "dalle",
    name: "DALL·E",
    tagline: "Text-to-image generation with style and photorealism",
    rating: 4.5,
    difficulty: "Easy",
    price: "$ Pay per image",
    prosCons: {
      pros: ["High quality", "Easy prompts", "Good for marketing"],
      cons: ["Costs can add up", "Style control limited"],
    },
  ctaLabel: "Try DALL·E",
  ctaHref: "https://openai.com/dall-e-3",
  logo: "/images/dalle.svg",
  categories: ["Images", "Design"],
  tags: ["OpenAI"],
  keywords: ["create images", "image generation", "marketing", "photorealistic images"],
  },
  {
    id: "sdxl",
    name: "Stable Diffusion XL",
    tagline: "Open image generation with strong community and control",
    rating: 4.5,
    difficulty: "Medium",
    price: "$ Free + hosted options",
    prosCons: {
      pros: ["Open ecosystem", "Fine-grained control", "Model choices"],
      cons: ["Setup complexity", "Tuning required"],
    },
  ctaLabel: "Explore SDXL",
  ctaHref: "https://stability.ai",
  logo: "/images/sdxl.svg",
  categories: ["Images"],
  tags: ["Open source", "Control"],
  keywords: ["image generation", "style transfer", "textures", "game assets"],
  },
  {
    id: "runway",
    name: "Runway",
    tagline: "Gen-3 video and creative AI tools for creators",
    rating: 4.6,
    difficulty: "Medium",
    price: "$ From $15/month",
    prosCons: {
      pros: ["Powerful video tools", "Web-based", "Rapid iteration"],
      cons: ["Requires GPU credits", "Learning curve"],
    },
  ctaLabel: "Try Runway",
  ctaHref: "https://runwayml.com",
  logo: "/images/runway.svg",
  categories: ["Video"],
  tags: ["Gen-3", "Creative"],
  keywords: ["make videos", "video generation", "video editing", "text to video", "image to video"],
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    tagline: "Realistic AI voices and speech synthesis at scale",
    rating: 4.7,
    difficulty: "Easy",
    price: "$ Free + Pro tiers",
    prosCons: {
      pros: ["Natural voices", "Fast cloning", "Great SSML"],
      cons: ["Licensing nuances", "Character limits"],
    },
  ctaLabel: "Try ElevenLabs",
  ctaHref: "https://elevenlabs.io",
  logo: "/images/elevenlabs.svg",
  categories: ["Audio", "Voice"],
  tags: ["TTS", "Cloning"],
  keywords: ["ai voice", "voice cloning", "text to speech", "voiceover", "dubbing", "sound effects", "sfx"],
  },
  {
    id: "descript",
    name: "Descript",
    tagline: "All‑in‑one audio/video editor with AI transcription and overdub",
    rating: 4.4,
    difficulty: "Medium",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Text-based editing", "Great for podcasts", "Transcription included"],
      cons: ["Desktop app heavy", "Export quirks"],
    },
  ctaLabel: "Try Descript",
  ctaHref: "https://www.descript.com",
  logo: "/images/descript.svg",
  categories: ["Audio", "Video", "Transcription"],
  tags: ["Overdub", "Text-based editing"],
  keywords: ["transcription", "speech to text", "podcast editing", "video editing"],
  },
  {
    id: "synthesia",
    name: "Synthesia",
    tagline: "Create AI videos with avatars and voiceovers from text",
    rating: 4.5,
    difficulty: "Easy",
    price: "$ From $22/month",
    prosCons: {
      pros: ["Quick video creation", "Many avatars", "Localization"],
      cons: ["Avatar uncanny valley", "Template feel"],
    },
  ctaLabel: "Try Synthesia",
  ctaHref: "https://www.synthesia.io",
  logo: "/images/synthesia.svg",
  categories: ["Video", "Presentations"],
  tags: ["Avatars"],
  keywords: ["avatar videos", "presentations", "localization", "voiceover"],
  },
  {
    id: "jasper",
    name: "Jasper",
    tagline: "AI marketing copilot for brand‑voice content and campaigns",
    rating: 4.3,
    difficulty: "Easy",
    price: "$ From $39/month",
    prosCons: {
      pros: ["Templates for marketers", "Brand voice", "Workflows"],
      cons: ["Pricey for teams", "Generic outputs sometimes"],
    },
  ctaLabel: "Try Jasper",
  ctaHref: "https://www.jasper.ai",
  logo: "/images/jasper.svg",
  categories: ["Writing", "Marketing"],
  tags: ["Brand voice"],
  keywords: [
      "marketing",
      "seo",
      "ad copy",
      "product descriptions",
      "brand voice",
      "campaigns",
      "workflows",
    ],
  },
  {
    id: "copyai",
    name: "Copy.ai",
    tagline: "AI copywriting for blogs, ads, emails, and product pages",
    rating: 4.2,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Quick drafts", "Simple UI", "Team features"],
      cons: ["Needs editing", "Inconsistent depth"],
    },
  ctaLabel: "Try Copy.ai",
  ctaHref: "https://www.copy.ai",
  logo: "/images/copyai.svg",
  categories: ["Writing", "Marketing"],
  tags: ["Copywriting"],
  keywords: ["copywriting", "blog posts", "newsletters", "rewrite", "paraphrase"],
  },
  {
    id: "canva",
    name: "Canva Magic Studio",
    tagline: "Design suite with AI tools for images, copy, and presentations",
    rating: 4.5,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["All-in-one", "Great templates", "Easy collaboration"],
      cons: ["Advanced design limits", "Export control"],
    },
    ctaLabel: "Open Canva",
  ctaHref: "https://www.canva.com/magic-studio",
  logo: "/images/canva.svg",
  categories: ["Design", "Presentations", "Images", "Writing"],
  tags: ["Templates", "Collaboration"],
  keywords: [
      "design logos",
      "presentations",
      "social media posts",
      "thumbnails",
      "brand kit",
      "remove background",
      "remove backgrounds",
      "background remover",
      "transparent background",
    ],
  },
  {
    id: "notion",
    name: "Notion AI",
  tagline: "Built‑in AI for notes, docs, and Q&A grounded in your workspace",
    rating: 4.4,
    difficulty: "Easy",
    price: "$ Add-on pricing",
    prosCons: {
      pros: ["Inside your docs", "Good summaries", "Ideation"],
      cons: ["Add-on cost", "Varies by content"],
    },
  ctaLabel: "Enable Notion AI",
  ctaHref: "https://www.notion.so/product/ai",
  logo: "/images/notion.svg",
    categories: ["Docs", "Productivity", "Automation"],
  tags: ["Notes", "Knowledge"],
  keywords: [
      "meeting notes",
      "summarize meetings",
      "knowledge base",
      "write docs",
      "wiki",
      "brainstorm",
      "action items",
    ],
  },
  {
    id: "codeium",
    name: "Codeium",
    tagline: "Free AI coding assistant for autocomplete and chat",
    rating: 4.3,
    difficulty: "Easy",
    price: "$ Free + Enterprise",
    prosCons: {
      pros: ["Free for individuals", "Many IDEs", "Solid completions"],
      cons: ["Varies by language", "Enterprise features gated"],
    },
  ctaLabel: "Try Codeium",
  ctaHref: "https://codeium.com",
  logo: "/images/codeium.svg",
  categories: ["Coding"],
  tags: ["Autocomplete"],
  keywords: ["code assistant", "code autocomplete", "debugging", "documentation"],
  },
  {
    id: "ms-copilot",
    name: "Microsoft Copilot",
    tagline: "AI assistant across Microsoft 365 and the web",
    rating: 4.4,
    difficulty: "Easy",
    price: "$ Add-on / included on some plans",
    prosCons: {
      pros: ["Deep M365 integration", "Good for enterprise", "Web answers"],
      cons: ["Licensing complexity", "Org setup required"],
    },
    ctaLabel: "Open Copilot",
  ctaHref: "https://copilot.microsoft.com",
  logo: "/images/ms-copilot.svg",
    categories: ["Chat", "Productivity", "Docs", "Automation"],
  tags: ["Microsoft 365"],
  keywords: ["microsoft 365", "excel formulas", "powerpoint", "word documents", "outlook", "email", "coaching", "teams", "web search"],
  },
  {
    id: "leonardo",
    name: "Leonardo AI",
    tagline: "Image generation with styles, models, and asset workflows",
    rating: 4.5,
    difficulty: "Medium",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Great styles", "Model control", "Asset tools"],
      cons: ["Learning curve", "Token costs"],
    },
  ctaLabel: "Try Leonardo",
  ctaHref: "https://leonardo.ai",
  logo: "/images/leonardo.svg",
  categories: ["Images", "Design"],
  tags: ["Models", "Assets"],
  keywords: ["create images", "image generation", "game assets", "icons", "textures"],
  },
  {
    id: "pika",
    name: "Pika",
    tagline: "AI video generation and editing from text and images",
    rating: 4.4,
    difficulty: "Medium",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["High-quality clips", "Fast iterations", "Community models"],
      cons: ["GPU/credit costs", "Prompt tuning"],
    },
  ctaLabel: "Try Pika",
  ctaHref: "https://pika.art",
  logo: "/images/pika.svg",
  categories: ["Video"],
  tags: ["Clips"],
  keywords: ["video generation", "shorts", "tiktok videos", "b-roll"],
  },
  {
    id: "tome",
    name: "Tome",
    tagline: "Create AI-powered presentations and docs quickly",
    rating: 4.2,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Fast decks", "Clean templates", "Embeds"],
      cons: ["Brand control limits", "Fine-tuning needed"],
    },
  ctaLabel: "Try Tome",
  ctaHref: "https://tome.app",
  logo: "/images/tome.svg",
  categories: ["Presentations", "Docs", "Writing"],
  tags: ["Decks"],
  keywords: ["presentations", "slides", "write content", "storyboards"],
  },
  // Background removal specialists
  {
    id: "removebg",
    name: "Remove.bg",
    tagline: "One‑click background removal for photos with API and batch",
    rating: 4.6,
    difficulty: "Easy",
    price: "$ Free preview + credits",
    prosCons: {
      pros: ["Very fast", "Good hair handling", "API + batch"],
      cons: ["Credit-based pricing", "Mixed results on complex glass"],
    },
  ctaLabel: "Remove background",
  ctaHref: "https://www.remove.bg/",
  logo: "/images/removebg.svg",
    categories: ["Images"],
    tags: ["Background remover", "Cutout"],
    keywords: [
      "remove background",
      "remove backgrounds",
      "background remover",
      "transparent background",
      "cutout",
      "image editing",
      "product photos",
      "ecommerce photos",
    ],
  },
  {
    id: "clipdrop-bg",
    name: "ClipDrop Background Remover",
    tagline: "High‑quality AI background remover by Stability AI",
    rating: 4.5,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Great edges", "Mobile + web", "Other tools included"],
      cons: ["Credits needed for HD", "Occasional halo"],
    },
  ctaLabel: "Open ClipDrop",
  ctaHref: "https://clipdrop.co/remove-background",
  logo: "/images/clipdrop.svg",
    categories: ["Images"],
    tags: ["Background remover", "Cutout"],
    keywords: [
      "remove background",
      "remove backgrounds",
      "background remover",
      "transparent background",
      "cutout",
      "image editing",
    ],
  },
  {
    id: "photoroom-bg",
    name: "PhotoRoom Background Remover",
  tagline: "Pro product photo cutouts with templates and batch tools",
    rating: 4.6,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Excellent product photos", "Batch tools", "Templates"],
      cons: ["Subscription for pro", "Branding on free exports"],
    },
  ctaLabel: "Open PhotoRoom",
  ctaHref: "https://www.photoroom.com/background-remover",
    logo: "/images/photoroom.svg",
    categories: ["Images"],
    tags: ["Background remover", "Ecommerce"],
    keywords: [
      "remove background",
      "remove backgrounds",
      "background remover",
      "product photos",
      "catalog",
      "transparent background",
    ],
  },
  {
    id: "adobe-express-bg",
    name: "Adobe Express Background Remover",
    tagline: "Free online background remover from Adobe",
    rating: 4.4,
    difficulty: "Easy",
    price: "$ Free + Premium",
    prosCons: {
      pros: ["Trusted brand", "Simple UI", "Works in browser"],
      cons: ["Account prompts", "Edge refinement needed sometimes"],
    },
  ctaLabel: "Open Adobe Express",
  ctaHref: "https://www.adobe.com/express/feature/image/remove-background",
    logo: "/images/adobe-express.svg",
    categories: ["Images"],
    tags: ["Background remover"],
    keywords: [
      "remove background",
      "remove backgrounds",
      "background remover",
      "transparent background",
      "cutout",
    ],
  },
  {
    id: "slazzer",
    name: "Slazzer",
    tagline: "Automatic background removal with API and plugins",
    rating: 4.3,
    difficulty: "Easy",
    price: "$ Free preview + credits",
    prosCons: {
      pros: ["API + plugins", "Batch processing", "Quick"],
      cons: ["Credit model", "Edges vary by photo"],
    },
  ctaLabel: "Open Slazzer",
  ctaHref: "https://www.slazzer.com/",
    logo: "/images/slazzer.svg",
    categories: ["Images"],
    tags: ["Background remover", "API"],
    keywords: [
      "remove background",
      "remove backgrounds",
      "background remover",
      "transparent background",
      "batch",
      "api",
    ],
  },
  {
    id: "icons8-bg",
    name: "Icons8 Background Remover",
    tagline: "Quick free background remover with simple controls",
    rating: 4.2,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Free tier", "Simple UI", "Good for portraits"],
      cons: ["Lower res on free", "Manual touch‑ups sometimes"],
    },
  ctaLabel: "Open Icons8",
  ctaHref: "https://icons8.com/bgremover",
    logo: "/images/icons8.svg",
  categories: ["Images"],
    tags: ["Background remover"],
    keywords: [
      "remove background",
      "remove backgrounds",
      "background remover",
      "transparent background",
      "cutout",
    ],
  },
  {
    id: "pixlr-bg",
    name: "Pixlr Remove Background",
    tagline: "Fast online background remover by Pixlr",
    rating: 4.2,
    difficulty: "Easy",
    price: "$ Free + Premium",
    prosCons: {
      pros: ["No signup needed", "Pretty fast", "Good for simple shots"],
      cons: ["Artifacts on fine detail", "Ads in free tier"],
    },
  ctaLabel: "Open Pixlr",
  ctaHref: "https://pixlr.com/remove-background/",
    logo: "/images/pixlr.svg",
    categories: ["Images"],
    tags: ["Background remover"],
    keywords: [
      "remove background",
      "remove backgrounds",
      "background remover",
      "transparent background",
    ],
  },
  {
    id: "kapwing-bg",
    name: "Kapwing Background Remover",
    tagline: "Remove image backgrounds online, integrates with editor",
    rating: 4.1,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Editor integration", "Templates", "Teams"],
      cons: ["Export limits on free", "Edges need cleanup sometimes"],
    },
  ctaLabel: "Open Kapwing",
  ctaHref: "https://www.kapwing.com/tools/remove-background",
    logo: "/images/kapwing.svg",
    categories: ["Images"],
    tags: ["Background remover", "Editor"],
    keywords: [
      "remove background",
      "remove backgrounds",
      "background remover",
      "transparent background",
      "cutout",
      "image editing",
    ],
  },
  {
    id: "v0",
    name: "v0",
    tagline: "Generate production‑ready React/Next.js UI from prompts or screenshots",
    rating: 4.5,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Fast UI generation", "Clean Tailwind/React code", "Great for prototypes"],
      cons: ["Still needs polishing", "Complex layouts may need tweaks"],
    },
    ctaLabel: "Open v0",
  ctaHref: "https://v0.dev",
  logo: "/images/v0.svg",
    categories: ["Design", "Coding", "UI"],
    tags: ["Design to code", "React", "Next.js", "Tailwind", "shadcn/ui"],
    keywords: [
      "v0",
      "v0.dev",
      "ui generator",
      "design to code",
      "screenshot to code",
      "figma to code",
      "react components",
      "nextjs",
      "tailwind",
      "shadcn",
      "landing pages",
      "dashboards",
      "component library",
      "code export",
    ],
  },
  {
    id: "lovable",
    name: "Lovable",
    tagline: "AI app developer that builds full‑stack apps from natural language",
    rating: 4.4,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["End‑to‑end app scaffolding", "One‑click deploy", "Good for CRUD"],
      cons: ["Manual refinement needed", "Complex backends need guidance"],
    },
    ctaLabel: "Open Lovable",
  ctaHref: "https://lovable.dev",
  logo: "/images/lovable.svg",
    categories: ["Coding", "App Builder"],
    tags: ["Full‑stack", "Scaffold", "Deploy"],
    keywords: [
      "lovable",
      "loveable",
      "lovable.dev",
      "app builder",
      "generate app",
      "full stack",
      "saas starter",
      "crud",
      "auth",
      "database",
      "stripe",
      "react",
      "nextjs",
      "tailwind",
      "deploy",
      "vercel",
      "github repo",
      "code generation",
      "agent",
    ],
  },
  // Added from Marketer Milk "26 best AI marketing tools" article
  {
    id: "gumloop",
    name: "Gumloop",
    tagline: "No-code AI automations connecting LLMs to your tools and data",
    rating: 4.5,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Built-in LLM access", "Great UI", "Agents & scraping"],
      cons: ["Credits for heavy use"],
    },
    ctaLabel: "Open Gumloop",
    ctaHref: "https://gumloop.com",
    categories: ["Automation", "Agents"],
    tags: ["Workflows", "MCP"],
    keywords: ["automations", "ai agents", "scrape websites", "connect tools", "no code"],
  },
  {
    id: "surfer-seo",
    name: "Surfer SEO",
    tagline: "SEO content optimizer with guidelines, scores, and SERP data",
    rating: 4.4,
    difficulty: "Medium",
    price: "$ Pro plans",
    prosCons: {
      pros: ["Actionable guidelines", "Integrations", "Outlines"],
      cons: ["Requires human edits", "Paid plans"],
    },
    ctaLabel: "Open Surfer SEO",
    ctaHref: "https://surferseo.com",
    categories: ["SEO", "Writing"],
    tags: ["Optimization", "Guidelines"],
    keywords: ["seo score", "content optimizer", "keywords", "outlines"],
  },
  {
    id: "lexica",
    name: "Lexica Art",
    tagline: "High-quality AI image generation for realistic thumbnails",
    rating: 4.4,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Photorealistic", "Prompt presets", "On-brand visuals"],
      cons: ["Prompt tuning needed"],
    },
    ctaLabel: "Open Lexica",
    ctaHref: "https://lexica.art",
    categories: ["Images", "Design"],
    tags: ["Thumbnails", "Photorealistic"],
    keywords: ["blog thumbnails", "image generator", "prompts", "brand visuals"],
  },
  {
    id: "lalal",
    name: "LALAL.AI",
    tagline: "AI stem separation and noise removal for cleaner audio",
    rating: 4.3,
    difficulty: "Easy",
    price: "$ Free preview + paid",
    prosCons: {
      pros: ["Removes background noise", "Preserves voice quality"],
      cons: ["Export limits on free"],
    },
    ctaLabel: "Open LALAL.AI",
    ctaHref: "https://www.lalal.ai",
    categories: ["Audio"],
    tags: ["Noise removal", "Stems"],
    keywords: ["remove noise", "clean audio", "podcast", "youtube audio"],
  },
  {
    id: "crayo",
    name: "Crayo",
    tagline: "Short-form video ideation and creation for TikTok, Reels, Shorts",
    rating: 4.2,
    difficulty: "Medium",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Creator-led", "Viral formats", "Faster production"],
      cons: ["GPU/credits for renders"],
    },
    ctaLabel: "Open Crayo",
    ctaHref: "https://crayo.ai",
    categories: ["Video"],
    tags: ["Shorts", "TikTok"],
    keywords: ["short form", "reels", "tiktok videos", "voiceover"],
  },
  {
    id: "brandwell",
    name: "Brandwell",
    tagline: "Generate long-form SEO blog posts with human-like quality",
    rating: 4.2,
    difficulty: "Easy",
    price: "$ Pro plans",
    prosCons: {
      pros: ["Passes detectors often", "Solid drafts"],
      cons: ["New UI quirks", "Still needs editing"],
    },
    ctaLabel: "Open Brandwell",
    ctaHref: "https://brandwell.ai",
    categories: ["Writing", "SEO"],
    tags: ["Blog posts"],
    keywords: ["seo articles", "long form", "content generation"],
  },
  {
    id: "originality-ai",
    name: "Originality AI",
    tagline: "AI content detector and plagiarism checking for drafts",
    rating: 4.1,
    difficulty: "Easy",
    price: "$ Paid",
    prosCons: {
      pros: ["Detects AI", "Plagiarism checks"],
      cons: ["False positives possible"],
    },
    ctaLabel: "Open Originality AI",
    ctaHref: "https://originality.ai",
    categories: ["Writing", "Compliance"],
    tags: ["Detection", "Plagiarism"],
    keywords: ["ai detection", "plagiarism check", "content quality"],
  },
  {
    id: "writer-com",
    name: "Writer",
    tagline: "Team writing assistant with style guides and terminology",
    rating: 4.2,
    difficulty: "Easy",
    price: "$ Pro plans",
    prosCons: {
      pros: ["Brand voice", "Snippets", "Checks"],
      cons: ["Enterprise pricing"],
    },
    ctaLabel: "Open Writer",
    ctaHref: "https://writer.com",
    categories: ["Writing", "Productivity"],
  tags: ["Style guide", "Teams", "Compliance"],
  keywords: ["terminology", "brand voice", "grammar", "snippets", "compliance"],
  },
  {
    id: "undetectable-ai",
    name: "Undetectable AI",
    tagline: "Rewrite AI-generated text to sound more human",
    rating: 4.0,
    difficulty: "Easy",
    price: "$ Paid",
    prosCons: {
      pros: ["Humanize AI text"],
      cons: ["Sometimes awkward", "Manual review needed"],
    },
    ctaLabel: "Open Undetectable AI",
    ctaHref: "https://undetectable.ai",
    categories: ["Writing"],
    tags: ["Rewriter"],
    keywords: ["humanize ai", "rewrite content", "bypass detectors"],
  },
  {
    id: "contentshake",
    name: "ContentShake AI",
    tagline: "Semrush-powered SEO writing with outlines and optimization",
    rating: 4.2,
    difficulty: "Easy",
    price: "$ Pro plans",
    prosCons: {
      pros: ["Semrush data", "Brand voice", "Publish to Docs/WordPress"],
      cons: ["Paid add-on"],
    },
    ctaLabel: "Open ContentShake",
    ctaHref: "https://www.semrush.com/",
    categories: ["SEO", "Writing"],
    tags: ["Semrush", "Optimization"],
    keywords: ["seo outlines", "optimization score", "brand voice"],
  },
  {
    id: "fullstory",
    name: "FullStory",
    tagline: "Digital experience analytics with session replay and insights",
    rating: 4.3,
    difficulty: "Medium",
    price: "$ Pro plans",
    prosCons: {
      pros: ["Session replay", "DX insights"],
      cons: ["Setup/consent needed"],
    },
    ctaLabel: "Open FullStory",
    ctaHref: "https://www.fullstory.com",
    categories: ["Analytics"],
    tags: ["Session replay", "DX"],
    keywords: ["user journeys", "heatmaps", "conversion issues"],
  },
  {
    id: "zapier",
    name: "Zapier",
    tagline: "Automate workflows across 3,000+ apps with no code",
    rating: 4.5,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Huge integrations", "Templates", "Branching"],
      cons: ["Complex at scale", "Task caps"],
    },
    ctaLabel: "Open Zapier",
    ctaHref: "https://zapier.com",
    categories: ["Automation"],
    tags: ["Integrations", "No code"],
    keywords: ["zaps", "automation", "workflows", "integrate apps"],
  },
  {
    id: "hemingway",
    name: "Hemingway App",
    tagline: "Free readability editor to tighten and clarify your writing",
    rating: 4.3,
    difficulty: "Easy",
    price: "$ Free + $20 desktop",
    prosCons: {
      pros: ["Simple UI", "Clear guidance", "Free online"],
      cons: ["Style constraints"],
    },
    ctaLabel: "Open Hemingway",
    ctaHref: "https://hemingwayapp.com",
    categories: ["Writing", "Editing"],
    tags: ["Readability"],
    keywords: ["grade level", "passive voice", "long sentences"],
  },
  {
    id: "chatfuel",
    name: "Chatfuel",
    tagline: "Build custom chatbots with drag‑and‑drop and Meta integration",
    rating: 4.2,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["No-code", "Meta partner"],
      cons: ["Tuning needed"],
    },
    ctaLabel: "Open Chatfuel",
    ctaHref: "https://chatfuel.com",
  categories: ["Chatbots", "Support"],
    tags: ["Drag-and-drop"],
    keywords: ["chatbots", "faq", "lead capture", "facebook"],
  },
  {
    id: "grammarly",
    name: "Grammarly",
    tagline: "Real-time grammar, clarity, and tone suggestions everywhere",
    rating: 4.6,
    difficulty: "Easy",
    price: "$ Free + Premium",
    prosCons: {
      pros: ["Wide integrations", "Strong grammar AI"],
      cons: ["Premium for full features"],
    },
    ctaLabel: "Open Grammarly",
    ctaHref: "https://www.grammarly.com",
    categories: ["Writing", "Editing"],
    tags: ["Grammar", "Tone"],
    keywords: ["spell check", "grammar", "clarity", "style"],
  },
  {
    id: "albert",
    name: "Albert.ai",
    tagline: "AI-driven ad optimization across social and search",
    rating: 4.1,
    difficulty: "Medium",
    price: "$ Pro plans",
    prosCons: {
      pros: ["Budget efficiency", "Personalization"],
      cons: ["Learning period"],
    },
    ctaLabel: "Open Albert.ai",
    ctaHref: "https://albert.ai",
    categories: ["Ads", "Marketing"],
    tags: ["Optimization"],
    keywords: ["ad optimization", "facebook ads", "google ads"],
  },
  {
    id: "headlime",
    name: "Headlime",
    tagline: "Landing page copy generation with templates and builder",
    rating: 4.0,
    difficulty: "Easy",
    price: "$ Pro plans",
    prosCons: {
      pros: ["Templates", "Multi-language"],
      cons: ["Generic outputs sometimes"],
    },
    ctaLabel: "Open Headlime",
    ctaHref: "https://headlime.com",
    categories: ["Writing", "Landing Pages"],
    tags: ["Templates"],
    keywords: ["landing page", "headlines", "conversion copy"],
  },
  {
    id: "userbot",
    name: "Userbot.ai",
    tagline: "Hybrid chat automation with human handoff and learning",
    rating: 4.0,
    difficulty: "Medium",
    price: "$ Pro plans",
    prosCons: {
      pros: ["Learns from operators", "CRM integrations"],
      cons: ["Setup and training time"],
    },
    ctaLabel: "Open Userbot",
    ctaHref: "https://userbot.ai",
    categories: ["Chatbots", "Support"],
    tags: ["Handoff"],
    keywords: ["customer support", "sales chat", "handoff"],
  },
  {
    id: "browse-ai",
    name: "Browse AI",
    tagline: "Train bots to scrape websites and fill spreadsheets automatically",
    rating: 4.3,
    difficulty: "Medium",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Easy bot training", "CI use cases"],
      cons: ["Anti-bot protections"],
    },
    ctaLabel: "Open Browse AI",
    ctaHref: "https://www.browse.ai",
    categories: ["Data", "Automation"],
    tags: ["Scraping"],
    keywords: ["scrape pages", "export to sheets", "competitive intel"],
  },
  {
    id: "algolia",
    name: "Algolia",
    tagline: "Hosted search and recommendations API for your site or app",
    rating: 4.5,
    difficulty: "Medium",
    price: "$ Free tier + Pro",
    prosCons: {
      pros: ["Fast", "Great docs", "Personalization"],
      cons: ["Developer setup"],
    },
    ctaLabel: "Open Algolia",
    ctaHref: "https://www.algolia.com",
    categories: ["Search", "Personalization"],
    tags: ["API", "Recommendations"],
    keywords: ["site search", "autocomplete", "recommendations"],
  },
  {
    id: "reply-io-email",
    name: "Reply.io Sales Email Assistant",
    tagline: "Generate replies and automate outreach with AI scoring",
    rating: 4.1,
    difficulty: "Easy",
    price: "$ Pro plans",
    prosCons: {
      pros: ["Sequence automation", "Lead scoring"],
      cons: ["Inbox warmup needed"],
    },
    ctaLabel: "Open Reply.io",
    ctaHref: "https://reply.io/sales-email-assistant",
    categories: ["Email", "Sales"],
    tags: ["Replies", "Sequences"],
    keywords: ["cold email", "reply generator", "sales engagement"],
  },
  {
    id: "brand24",
    name: "Brand24",
    tagline: "Media monitoring and sentiment analysis across the web",
    rating: 4.3,
    difficulty: "Easy",
    price: "$ Pro plans",
    prosCons: {
      pros: ["Mentions tracking", "Trends", "Alerts"],
      cons: ["Noise needs filtering"],
    },
    ctaLabel: "Open Brand24",
    ctaHref: "https://brand24.com",
  categories: ["Monitoring", "Analytics"],
    tags: ["Sentiment", "Social"],
    keywords: ["brand mentions", "sentiment", "hashtag trends"],
  },
  {
    id: "influencity",
    name: "Influencity",
    tagline: "End-to-end influencer marketing: discovery, outreach, tracking",
    rating: 4.2,
    difficulty: "Medium",
    price: "$ Pro plans",
    prosCons: {
      pros: ["Large database", "Campaign tracking"],
      cons: ["Learning curve"],
    },
    ctaLabel: "Open Influencity",
    ctaHref: "https://influencity.com",
    categories: ["Influencer", "Social"],
    tags: ["Discovery", "Measurement"],
    keywords: ["find influencers", "campaigns", "instagram", "tiktok"],
  },
  // Added from Zapier "best AI productivity tools" 2024/2025 roundup
  {
    id: "wordtune",
    name: "Wordtune",
    tagline: "Rewrite, shorten, and expand sentences with tone control",
    rating: 4.3,
    difficulty: "Easy",
    price: "$ Free + Premium",
    prosCons: { pros: ["Great rewrites", "Tone options"], cons: ["Free limits"] },
    ctaLabel: "Open Wordtune",
    ctaHref: "https://www.wordtune.com/",
    categories: ["Writing", "Editing"],
    tags: ["Rewriting", "Tone"],
    keywords: ["rewrite", "shorten", "expand", "tone", "synonyms"],
  },
  {
    id: "prowritingaid",
    name: "ProWritingAid",
    tagline: "Grammar, style reports, and lifetime plan for writers",
    rating: 4.2,
    difficulty: "Easy",
    price: "$ Free + Premium + Lifetime",
    prosCons: { pros: ["Detailed reports", "One-time lifetime option"], cons: ["Overwhelming stats"] },
    ctaLabel: "Open ProWritingAid",
    ctaHref: "https://prowritingaid.com/",
    categories: ["Writing", "Editing"],
    tags: ["Grammar", "Style"],
    keywords: ["grammar", "style", "readability", "reports"],
  },
  {
    id: "filmora",
    name: "Wondershare Filmora",
    tagline: "Classic video editor with AI background removal and denoise",
    rating: 4.2,
    difficulty: "Medium",
    price: "$ Free trial + Pro",
    prosCons: { pros: ["Familiar UI", "AI cleanup"], cons: ["Export limits on free"] },
    ctaLabel: "Open Filmora",
    ctaHref: "https://filmora.wondershare.com/",
    categories: ["Video"],
    tags: ["Editing", "Enhance"],
    keywords: ["video editor", "denoise", "background removal", "ai tools"],
  },
  {
    id: "ideogram",
    name: "Ideogram",
    tagline: "AI image generator with accurate text rendering",
    rating: 4.3,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: { pros: ["Text in images", "Good quality"], cons: ["Public on free tier"] },
    ctaLabel: "Open Ideogram",
    ctaHref: "https://ideogram.ai/",
    categories: ["Images", "Design"],
    tags: ["Text in image"],
    keywords: ["image generator", "text in image", "posters", "signage"],
  },
  {
    id: "feedhive",
    name: "FeedHive",
    tagline: "AI-powered content recycling and conditional posting",
    rating: 4.3,
    difficulty: "Easy",
    price: "$ Pro plans",
    prosCons: { pros: ["Recycle posts", "Repurpose across networks"], cons: ["Learning curve"] },
    ctaLabel: "Open FeedHive",
    ctaHref: "https://www.feedhive.com/",
    categories: ["Social"],
    tags: ["Scheduling", "Repurpose"],
    keywords: ["content recycling", "schedule", "conditional posting"],
  },
  {
    id: "vista-social",
    name: "Vista Social",
    tagline: "Connect many social channels and repurpose content with AI",
    rating: 4.2,
    difficulty: "Easy",
    price: "$ Pro plans",
    prosCons: { pros: ["Many networks", "Repurpose"], cons: ["Setup time"] },
    ctaLabel: "Open Vista Social",
    ctaHref: "https://vistasocial.com/",
    categories: ["Social"],
    tags: ["Scheduling", "Repurpose"],
    keywords: ["social media", "schedule", "repurpose", "integrations"],
  },
  {
    id: "buffer",
    name: "Buffer",
    tagline: "Tailor posts to each channel and schedule with AI help",
    rating: 4.4,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: { pros: ["Channel-specific", "Ideas inbox"], cons: ["Free limits"] },
    ctaLabel: "Open Buffer",
    ctaHref: "https://buffer.com/",
    categories: ["Social"],
    tags: ["Scheduling"],
    keywords: ["schedule", "linkedin", "twitter", "facebook", "instagram"],
  },
  {
    id: "suno",
    name: "Suno",
    tagline: "Generate full songs with vocals from a simple prompt",
    rating: 4.3,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: { pros: ["Fun", "Fast results"], cons: ["IP considerations"] },
    ctaLabel: "Open Suno",
    ctaHref: "https://suno.com/",
    categories: ["Audio", "Music"],
    tags: ["Music", "Lyrics"],
    keywords: ["ai music", "lyrics", "vocals", "song generator"],
  },
  {
    id: "aiva",
    name: "AIVA",
    tagline: "Compose music by style, chords, or audio reference",
    rating: 4.1,
    difficulty: "Medium",
    price: "$ Free + Pro",
    prosCons: { pros: ["Composition control"], cons: ["Editing needed"] },
    ctaLabel: "Open AIVA",
    ctaHref: "https://www.aiva.ai/",
    categories: ["Audio", "Music"],
    tags: ["Composer"],
    keywords: ["compose", "orchestral", "soundtrack", "prompt to music"],
  },
  {
    id: "mem",
    name: "Mem",
    tagline: "Second brain with AI-powered tagging and search",
    rating: 4.2,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: { pros: ["Auto-tagging", "Great search"], cons: ["Adoption time"] },
    ctaLabel: "Open Mem",
    ctaHref: "https://mem.ai/",
    categories: ["Productivity", "Knowledge"],
    tags: ["Notes", "Second brain"],
    keywords: ["notes", "auto tag", "search", "knowledge"],
  },
  {
    id: "personal-ai",
    name: "Personal AI",
    tagline: "Message with an AI clone trained on your memories",
    rating: 4.0,
    difficulty: "Medium",
    price: "$ Free + Pro",
    prosCons: { pros: ["Autopilot replies"], cons: ["Training required"] },
    ctaLabel: "Open Personal AI",
    ctaHref: "https://www.personal.ai/",
    categories: ["Chat", "Productivity"],
    tags: ["Messaging", "Grounded"],
    keywords: ["memory", "auto reply", "personal knowledge"],
  },
  {
    id: "reclaim",
    name: "Reclaim",
    tagline: "Protect habits and defend task time on your calendar",
    rating: 4.3,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: { pros: ["Habit protection"], cons: ["Setup time"] },
    ctaLabel: "Open Reclaim",
    ctaHref: "https://reclaim.ai/",
    categories: ["Scheduling"],
    tags: ["Habits", "Calendar"],
    keywords: ["habits", "time blocking", "calendar"],
  },
  {
    id: "clockwise",
    name: "Clockwise",
    tagline: "Sync team calendars and find focus time automatically",
    rating: 4.2,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: { pros: ["Focus time"], cons: ["Org setup"] },
    ctaLabel: "Open Clockwise",
    ctaHref: "https://www.getclockwise.com/",
    categories: ["Scheduling"],
    tags: ["Teams", "Focus"],
    keywords: ["team calendar", "focus time", "meetings"],
  },
  {
    id: "motion",
    name: "Motion",
    tagline: "AI schedule assistant that plans work around priorities",
    rating: 4.2,
    difficulty: "Easy",
    price: "$ Pro plans",
    prosCons: { pros: ["Priority scheduling"], cons: ["Learning curve"] },
    ctaLabel: "Open Motion",
    ctaHref: "https://www.usemotion.com/",
    categories: ["Scheduling", "Project Management"],
    tags: ["Auto-plan", "Tasks"],
    keywords: ["auto schedule", "calendar", "priorities", "project management"],
  },
  {
    id: "shortwave",
    name: "Shortwave",
    tagline: "AI email assistant with deep thread summaries and search",
    rating: 4.4,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: { pros: ["Great summaries", "Natural language actions"], cons: ["Gmail only"] },
    ctaLabel: "Open Shortwave",
    ctaHref: "https://www.shortwave.com/",
    categories: ["Email"],
    tags: ["Inbox", "Summaries"],
    keywords: ["summarize emails", "email search", "gmail"],
  },
  {
    id: "beautiful-ai",
    name: "Beautiful.ai",
    tagline: "Build beautiful decks quickly with AI layout help",
    rating: 4.1,
    difficulty: "Easy",
    price: "$ Pro plans",
    prosCons: { pros: ["Great templates"], cons: ["Limited fine control"] },
    ctaLabel: "Open Beautiful.ai",
    ctaHref: "http://beautiful.ai/",
    categories: ["Presentations"],
    tags: ["Decks", "Templates"],
    keywords: ["presentations", "templates", "slides"],
  },
  {
    id: "slidesgo",
    name: "Slidesgo",
    tagline: "Generate full presentations from topic and tone",
    rating: 4.0,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: { pros: ["Fast generation"], cons: ["Needs edits"] },
    ctaLabel: "Open Slidesgo",
    ctaHref: "https://slidesgo.com/",
    categories: ["Presentations"],
    tags: ["Decks"],
    keywords: ["generate slides", "topics", "tone", "ai writing"],
  },
  {
    id: "teal",
    name: "Teal",
    tagline: "Track job applications and tailor resumes with AI",
    rating: 4.2,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: { pros: ["Job tracking"], cons: ["Manual data entry"] },
    ctaLabel: "Open Teal",
    ctaHref: "https://www.tealhq.com/tools/resume-builder",
    categories: ["Resume", "Career"],
    tags: ["ATS", "Tracking"],
    keywords: ["resume", "job tracker", "ats", "cover letter"],
  },
  {
    id: "enhancv",
    name: "Enhancv",
    tagline: "Optimize your resume with an AI assistant and ATS check",
    rating: 4.1,
    difficulty: "Easy",
    price: "$ Pro plans",
    prosCons: { pros: ["AI suggestions", "ATS score"], cons: ["Paywall features"] },
    ctaLabel: "Open Enhancv",
    ctaHref: "https://enhancv.com/ai-resume-builder/",
    categories: ["Resume", "Career"],
    tags: ["ATS", "Assistant"],
    keywords: ["resume", "ats", "optimization", "linkedin import"],
  },
  {
    id: "kickresume",
    name: "Kickresume",
    tagline: "Generate a resume from scratch with AI",
    rating: 4.0,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: { pros: ["From scratch"], cons: ["Fact-check needed"] },
    ctaLabel: "Open Kickresume",
    ctaHref: "https://www.kickresume.com/en/ai-resume-writer/",
    categories: ["Resume", "Career"],
    tags: ["Generator"],
    keywords: ["resume builder", "ai resume", "cv", "generator"],
  },
  {
    id: "avoma",
    name: "Avoma",
    tagline: "Conversation analytics, scoring, and topic tracking",
    rating: 4.3,
    difficulty: "Medium",
    price: "$ Pro plans",
    prosCons: { pros: ["Analytics", "Coaching"], cons: ["Org setup"] },
    ctaLabel: "Open Avoma",
    ctaHref: "https://www.avoma.com/",
    categories: ["Transcription", "Meetings"],
    tags: ["Analytics", "Coaching"],
    keywords: ["transcription", "sales calls", "coaching", "topics"],
  },
  {
    id: "tldv",
    name: "tl;dv",
    tagline: "Record, transcribe, clip, and search meetings with AI",
    rating: 4.4,
    difficulty: "Easy",
    price: "$ Free + Pro",
  prosCons: { pros: ["Generous free plan", "Clips"], cons: ["Limits on free exports"] },
    ctaLabel: "Open tl;dv",
    ctaHref: "https://tldv.io/ai-meeting-assistant/",
    categories: ["Transcription", "Meetings"],
    tags: ["Search", "Clips"],
    keywords: ["meeting recorder", "transcripts", "clips", "search"],
  },
  {
    id: "anydo",
    name: "Any.do",
    tagline: "Generate and organize tasks with AI suggestions",
    rating: 4.2,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: { pros: ["Task suggestions"], cons: ["Gmail-only email features"] },
    ctaLabel: "Open Any.do",
    ctaHref: "https://any.do/",
    categories: ["Task Management", "Productivity"],
    tags: ["Tasks"],
    keywords: ["task manager", "ai suggestions", "calendar"],
  },
  {
    id: "beedone",
    name: "BeeDone",
    tagline: "Gamify your tasks with AI guidance and habit tracking",
    rating: 4.0,
    difficulty: "Easy",
    price: "$ Pro plans",
    prosCons: { pros: ["Gamification"], cons: ["Quirky UI"] },
    ctaLabel: "Open BeeDone",
    ctaHref: "https://www.beedone.co/",
    categories: ["Task Management", "Productivity"],
    tags: ["Habits", "Gamification"],
    keywords: ["habits", "gamify", "task roulette", "routines"],
  },
];
