import type { ToolItem } from "@/types/tools";

export const tools: ToolItem[] = [
  {
    id: "chatgpt",
    name: "ChatGPT",
    tagline: "Conversational AI for writing, brainstorming, and problem-solving",
    rating: 4.8,
    difficulty: "Easy",
    price: "$ Free + $20/month",
    prosCons: {
      pros: ["Versatile", "Great for beginners", "Strong reasoning"],
      cons: ["Can be verbose", "Knowledge cutoff"],
    },
    ctaLabel: "Try ChatGPT",
    ctaHref: "https://chat.openai.com",
  categories: ["Chat", "Writing", "Research", "Coding"],
  tags: ["Generalist", "OpenAI", "GPT"],
    keywords: [
      "write content",
      "brainstorm",
      "summarize",
      "translate",
      "research",
      "reasoning",
      "math",
      "code assistant",
      "chatbots",
      "customer support",
      "knowledge base",
    ],
  },
  {
    id: "midjourney",
    name: "Midjourney",
    tagline: "AI image generator for stunning artwork and visuals",
    rating: 4.7,
    difficulty: "Medium",
    price: "$ 10–60/month",
    prosCons: {
      pros: ["Highest quality images", "Active community", "Unique artistic style"],
      cons: ["Discord-based", "Learning curve", "No free tier"],
    },
    ctaLabel: "Try Midjourney",
    ctaHref: "https://www.midjourney.com",
  categories: ["Images", "Design"],
  tags: ["Art", "Generative"],
    keywords: [
      "create images",
      "image generation",
      "concept art",
      "illustrations",
      "photorealistic images",
      "logos",
      "thumbnails",
    ],
  },
  {
    id: "claude",
    name: "Claude",
    tagline: "Helpful, honest, and harmless assistant for reasoning and writing",
    rating: 4.8,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Great long-context", "Strong writing", "Safe outputs"],
      cons: ["Occasional refusals", "Web access varies"],
    },
    ctaLabel: "Try Claude",
    ctaHref: "https://claude.ai",
  categories: ["Chat", "Writing", "Research"],
  tags: ["Long context", "Anthropic"],
    keywords: [
      "write content",
      "long context",
      "reasoning",
      "summarize",
      "research",
      "brainstorm",
      "knowledge base",
    ],
  },
  {
    id: "gemini",
    name: "Google Gemini",
    tagline: "Multimodal AI for text, images, and code with Google integration",
    rating: 4.6,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Strong search integration", "Multimodal", "Great for Google users"],
      cons: ["Inconsistent coding", "Occasional guardrails"],
    },
    ctaLabel: "Try Gemini",
    ctaHref: "https://gemini.google.com",
  categories: ["Chat", "Multimodal", "Coding"],
  tags: ["Google"],
    keywords: [
      "multimodal",
      "image understanding",
      "vision",
      "web search",
      "browsing",
      "write content",
    ],
  },
  {
    id: "perplexity",
    name: "Perplexity",
    tagline: "Answer engine with citations and focused research workflows",
    rating: 4.7,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Fast with sources", "Great browsing", "Good follow-ups"],
      cons: ["Limited creativity", "Pro features gated"],
    },
    ctaLabel: "Try Perplexity",
    ctaHref: "https://www.perplexity.ai",
  categories: ["Research", "Search"],
  tags: ["Citations", "Answer engine"],
  keywords: ["research", "answer engine", "citations", "web search", "browsing"],
  },
  {
    id: "copilot",
    name: "GitHub Copilot",
    tagline: "AI pair programmer for code suggestions and completions",
    rating: 4.6,
    difficulty: "Easy",
    price: "$ 10–19/user/month",
    prosCons: {
      pros: ["Boosts productivity", "Great editor integration", "Strong autocomplete"],
      cons: ["Hallucinated APIs", "Not a substitute for tests"],
    },
    ctaLabel: "Try GitHub Copilot",
    ctaHref: "https://github.com/features/copilot",
  categories: ["Coding"],
  tags: ["Autocomplete", "Pair programming"],
  keywords: ["code assistant", "generate code", "code autocomplete", "unit tests"],
  },
  {
    id: "dalle",
    name: "DALL·E",
    tagline: "Text-to-image generation with style and photorealism",
    rating: 4.5,
    difficulty: "Easy",
    price: "$ Pay per image",
    prosCons: {
      pros: ["High quality", "Easy prompts", "Good for marketing"],
      cons: ["Costs can add up", "Style control limited"],
    },
    ctaLabel: "Try DALL·E",
    ctaHref: "https://openai.com/dall-e-3",
  categories: ["Images", "Design"],
  tags: ["OpenAI"],
  keywords: ["create images", "image generation", "marketing", "photorealistic images"],
  },
  {
    id: "sdxl",
    name: "Stable Diffusion XL",
    tagline: "Open image generation with strong community and control",
    rating: 4.5,
    difficulty: "Medium",
    price: "$ Free + hosted options",
    prosCons: {
      pros: ["Open ecosystem", "Fine-grained control", "Model choices"],
      cons: ["Setup complexity", "Tuning required"],
    },
    ctaLabel: "Explore SDXL",
    ctaHref: "https://stability.ai",
  categories: ["Images"],
  tags: ["Open source", "Control"],
  keywords: ["image generation", "style transfer", "textures", "game assets"],
  },
  {
    id: "runway",
    name: "Runway",
    tagline: "Gen-3 video and creative AI tools for creators",
    rating: 4.6,
    difficulty: "Medium",
    price: "$ From $15/month",
    prosCons: {
      pros: ["Powerful video tools", "Web-based", "Rapid iteration"],
      cons: ["Requires GPU credits", "Learning curve"],
    },
    ctaLabel: "Try Runway",
    ctaHref: "https://runwayml.com",
  categories: ["Video"],
  tags: ["Gen-3", "Creative"],
  keywords: ["make videos", "video generation", "video editing", "text to video", "image to video"],
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    tagline: "Realistic AI voices and speech synthesis at scale",
    rating: 4.7,
    difficulty: "Easy",
    price: "$ Free + Pro tiers",
    prosCons: {
      pros: ["Natural voices", "Fast cloning", "Great SSML"],
      cons: ["Licensing nuances", "Character limits"],
    },
    ctaLabel: "Try ElevenLabs",
    ctaHref: "https://elevenlabs.io",
  categories: ["Audio", "Voice"],
  tags: ["TTS", "Cloning"],
  keywords: ["ai voice", "voice cloning", "text to speech", "voiceover", "dubbing"],
  },
  {
    id: "descript",
    name: "Descript",
    tagline: "All‑in‑one audio/video editor with AI transcription and overdub",
    rating: 4.4,
    difficulty: "Medium",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Text-based editing", "Great for podcasts", "Transcription included"],
      cons: ["Desktop app heavy", "Export quirks"],
    },
    ctaLabel: "Try Descript",
    ctaHref: "https://www.descript.com",
  categories: ["Audio", "Video", "Transcription"],
  tags: ["Overdub", "Text-based editing"],
  keywords: ["transcription", "speech to text", "podcast editing", "video editing"],
  },
  {
    id: "synthesia",
    name: "Synthesia",
    tagline: "Create AI videos with avatars and voiceovers from text",
    rating: 4.5,
    difficulty: "Easy",
    price: "$ From $22/month",
    prosCons: {
      pros: ["Quick video creation", "Many avatars", "Localization"],
      cons: ["Avatar uncanny valley", "Template feel"],
    },
    ctaLabel: "Try Synthesia",
    ctaHref: "https://www.synthesia.io",
  categories: ["Video", "Presentations"],
  tags: ["Avatars"],
  keywords: ["avatar videos", "presentations", "localization", "voiceover"],
  },
  {
    id: "jasper",
    name: "Jasper",
    tagline: "Marketing-focused AI writing and brand voice tools",
    rating: 4.3,
    difficulty: "Easy",
    price: "$ From $39/month",
    prosCons: {
      pros: ["Templates for marketers", "Brand voice", "Workflows"],
      cons: ["Pricey for teams", "Generic outputs sometimes"],
    },
    ctaLabel: "Try Jasper",
    ctaHref: "https://www.jasper.ai",
  categories: ["Writing", "Marketing"],
  tags: ["Brand voice"],
  keywords: ["marketing", "seo", "ad copy", "product descriptions", "brand voice"],
  },
  {
    id: "copyai",
    name: "Copy.ai",
    tagline: "AI copywriting for blogs, ads, emails, and product pages",
    rating: 4.2,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Quick drafts", "Simple UI", "Team features"],
      cons: ["Needs editing", "Inconsistent depth"],
    },
    ctaLabel: "Try Copy.ai",
    ctaHref: "https://www.copy.ai",
  categories: ["Writing", "Marketing"],
  tags: ["Copywriting"],
  keywords: ["copywriting", "blog posts", "newsletters", "rewrite", "paraphrase"],
  },
  {
    id: "canva",
    name: "Canva Magic Studio",
    tagline: "Design suite with AI tools for images, copy, and presentations",
    rating: 4.5,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["All-in-one", "Great templates", "Easy collaboration"],
      cons: ["Advanced design limits", "Export control"],
    },
    ctaLabel: "Open Canva",
    ctaHref: "https://www.canva.com/magic-studio",
  categories: ["Design", "Presentations", "Images", "Writing"],
  tags: ["Templates", "Collaboration"],
  keywords: [
      "design logos",
      "presentations",
      "social media posts",
      "thumbnails",
      "brand kit",
      "remove background",
      "remove backgrounds",
      "background remover",
      "transparent background",
    ],
  },
  {
    id: "notion",
    name: "Notion AI",
    tagline: "Integrated AI for docs, notes, and knowledge bases",
    rating: 4.4,
    difficulty: "Easy",
    price: "$ Add-on pricing",
    prosCons: {
      pros: ["Inside your docs", "Good summaries", "Ideation"],
      cons: ["Add-on cost", "Varies by content"],
    },
    ctaLabel: "Enable Notion AI",
    ctaHref: "https://www.notion.so/product/ai",
  categories: ["Docs", "Productivity"],
  tags: ["Notes", "Knowledge"],
  keywords: ["meeting notes", "summarize meetings", "knowledge base", "write docs"],
  },
  {
    id: "codeium",
    name: "Codeium",
    tagline: "Free AI coding assistant for autocomplete and chat",
    rating: 4.3,
    difficulty: "Easy",
    price: "$ Free + Enterprise",
    prosCons: {
      pros: ["Free for individuals", "Many IDEs", "Solid completions"],
      cons: ["Varies by language", "Enterprise features gated"],
    },
    ctaLabel: "Try Codeium",
    ctaHref: "https://codeium.com",
  categories: ["Coding"],
  tags: ["Autocomplete"],
  keywords: ["code assistant", "code autocomplete", "debugging", "documentation"],
  },
  {
    id: "ms-copilot",
    name: "Microsoft Copilot",
    tagline: "AI assistant across Microsoft 365 and the web",
    rating: 4.4,
    difficulty: "Easy",
    price: "$ Add-on / included on some plans",
    prosCons: {
      pros: ["Deep M365 integration", "Good for enterprise", "Web answers"],
      cons: ["Licensing complexity", "Org setup required"],
    },
    ctaLabel: "Open Copilot",
    ctaHref: "https://copilot.microsoft.com",
  categories: ["Chat", "Productivity", "Docs"],
  tags: ["Microsoft 365"],
  keywords: ["microsoft 365", "excel formulas", "powerpoint", "word documents", "web search"],
  },
  {
    id: "leonardo",
    name: "Leonardo AI",
    tagline: "Image generation with styles, models, and asset workflows",
    rating: 4.5,
    difficulty: "Medium",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Great styles", "Model control", "Asset tools"],
      cons: ["Learning curve", "Token costs"],
    },
    ctaLabel: "Try Leonardo",
    ctaHref: "https://leonardo.ai",
  categories: ["Images", "Design"],
  tags: ["Models", "Assets"],
  keywords: ["create images", "image generation", "game assets", "icons", "textures"],
  },
  {
    id: "pika",
    name: "Pika",
    tagline: "AI video generation and editing from text and images",
    rating: 4.4,
    difficulty: "Medium",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["High-quality clips", "Fast iterations", "Community models"],
      cons: ["GPU/credit costs", "Prompt tuning"],
    },
    ctaLabel: "Try Pika",
    ctaHref: "https://pika.art",
  categories: ["Video"],
  tags: ["Clips"],
  keywords: ["video generation", "shorts", "tiktok videos", "b-roll"],
  },
  {
    id: "tome",
    name: "Tome",
    tagline: "Create AI-powered presentations and docs quickly",
    rating: 4.2,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Fast decks", "Clean templates", "Embeds"],
      cons: ["Brand control limits", "Fine-tuning needed"],
    },
    ctaLabel: "Try Tome",
    ctaHref: "https://tome.app",
  categories: ["Presentations", "Docs", "Writing"],
  tags: ["Decks"],
  keywords: ["presentations", "slides", "write content", "storyboards"],
  },
  // Background removal specialists
  {
    id: "removebg",
    name: "Remove.bg",
    tagline: "One‑click background removal for photos with API and batch",
    rating: 4.6,
    difficulty: "Easy",
    price: "$ Free preview + credits",
    prosCons: {
      pros: ["Very fast", "Good hair handling", "API + batch"],
      cons: ["Credit-based pricing", "Mixed results on complex glass"],
    },
    ctaLabel: "Remove background",
    ctaHref: "https://www.remove.bg/",
    categories: ["Images"],
    tags: ["Background remover", "Cutout"],
    keywords: [
      "remove background",
      "remove backgrounds",
      "background remover",
      "transparent background",
      "cutout",
      "image editing",
      "product photos",
      "ecommerce photos",
    ],
  },
  {
    id: "clipdrop-bg",
    name: "ClipDrop Background Remover",
    tagline: "High‑quality AI background remover by Stability AI",
    rating: 4.5,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Great edges", "Mobile + web", "Other tools included"],
      cons: ["Credits needed for HD", "Occasional halo"],
    },
    ctaLabel: "Open ClipDrop",
    ctaHref: "https://clipdrop.co/remove-background",
    categories: ["Images"],
    tags: ["Background remover", "Cutout"],
    keywords: [
      "remove background",
      "remove backgrounds",
      "background remover",
      "transparent background",
      "cutout",
      "image editing",
    ],
  },
  {
    id: "photoroom-bg",
    name: "PhotoRoom Background Remover",
    tagline: "Ecommerce‑ready cutouts with templates and batch",
    rating: 4.6,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Excellent product photos", "Batch tools", "Templates"],
      cons: ["Subscription for pro", "Branding on free exports"],
    },
    ctaLabel: "Open PhotoRoom",
    ctaHref: "https://www.photoroom.com/background-remover",
    categories: ["Images"],
    tags: ["Background remover", "Ecommerce"],
    keywords: [
      "remove background",
      "remove backgrounds",
      "background remover",
      "product photos",
      "catalog",
      "transparent background",
    ],
  },
  {
    id: "adobe-express-bg",
    name: "Adobe Express Background Remover",
    tagline: "Free online background remover from Adobe",
    rating: 4.4,
    difficulty: "Easy",
    price: "$ Free + Premium",
    prosCons: {
      pros: ["Trusted brand", "Simple UI", "Works in browser"],
      cons: ["Account prompts", "Edge refinement needed sometimes"],
    },
    ctaLabel: "Open Adobe Express",
    ctaHref: "https://www.adobe.com/express/feature/image/remove-background",
    categories: ["Images"],
    tags: ["Background remover"],
    keywords: [
      "remove background",
      "remove backgrounds",
      "background remover",
      "transparent background",
      "cutout",
    ],
  },
  {
    id: "slazzer",
    name: "Slazzer",
    tagline: "Automatic background removal with API and plugins",
    rating: 4.3,
    difficulty: "Easy",
    price: "$ Free preview + credits",
    prosCons: {
      pros: ["API + plugins", "Batch processing", "Quick"],
      cons: ["Credit model", "Edges vary by photo"],
    },
    ctaLabel: "Open Slazzer",
    ctaHref: "https://www.slazzer.com/",
    categories: ["Images"],
    tags: ["Background remover", "API"],
    keywords: [
      "remove background",
      "remove backgrounds",
      "background remover",
      "transparent background",
      "batch",
      "api",
    ],
  },
  {
    id: "icons8-bg",
    name: "Icons8 Background Remover",
    tagline: "Quick free background remover with simple controls",
    rating: 4.2,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Free tier", "Simple UI", "Good for portraits"],
      cons: ["Lower res on free", "Manual touch‑ups sometimes"],
    },
    ctaLabel: "Open Icons8",
    ctaHref: "https://icons8.com/bgremover",
    categories: ["Images"],
    tags: ["Background remover"],
    keywords: [
      "remove background",
      "remove backgrounds",
      "background remover",
      "transparent background",
      "cutout",
    ],
  },
  {
    id: "pixlr-bg",
    name: "Pixlr Remove Background",
    tagline: "Fast online background remover by Pixlr",
    rating: 4.2,
    difficulty: "Easy",
    price: "$ Free + Premium",
    prosCons: {
      pros: ["No signup needed", "Pretty fast", "Good for simple shots"],
      cons: ["Artifacts on fine detail", "Ads in free tier"],
    },
    ctaLabel: "Open Pixlr",
    ctaHref: "https://pixlr.com/remove-background/",
    categories: ["Images"],
    tags: ["Background remover"],
    keywords: [
      "remove background",
      "remove backgrounds",
      "background remover",
      "transparent background",
    ],
  },
  {
    id: "kapwing-bg",
    name: "Kapwing Background Remover",
    tagline: "Remove image backgrounds online, integrates with editor",
    rating: 4.1,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Editor integration", "Templates", "Teams"],
      cons: ["Export limits on free", "Edges need cleanup sometimes"],
    },
    ctaLabel: "Open Kapwing",
    ctaHref: "https://www.kapwing.com/tools/remove-background",
    categories: ["Images"],
    tags: ["Background remover", "Editor"],
    keywords: [
      "remove background",
      "remove backgrounds",
      "background remover",
      "transparent background",
      "cutout",
      "image editing",
    ],
  },
  {
    id: "v0",
    name: "v0",
    tagline: "Generate production‑ready React/Next.js UI from prompts or screenshots",
    rating: 4.5,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["Fast UI generation", "Clean Tailwind/React code", "Great for prototypes"],
      cons: ["Still needs polishing", "Complex layouts may need tweaks"],
    },
    ctaLabel: "Open v0",
    ctaHref: "https://v0.dev",
    categories: ["Design", "Coding", "UI"],
    tags: ["Design to code", "React", "Next.js", "Tailwind", "shadcn/ui"],
    keywords: [
      "v0",
      "v0.dev",
      "ui generator",
      "design to code",
      "screenshot to code",
      "figma to code",
      "react components",
      "nextjs",
      "tailwind",
      "shadcn",
      "landing pages",
      "dashboards",
      "component library",
      "code export",
    ],
  },
  {
    id: "lovable",
    name: "Lovable",
    tagline: "AI app developer that builds full‑stack apps from natural language",
    rating: 4.4,
    difficulty: "Easy",
    price: "$ Free + Pro",
    prosCons: {
      pros: ["End‑to‑end app scaffolding", "One‑click deploy", "Good for CRUD"],
      cons: ["Manual refinement needed", "Complex backends need guidance"],
    },
    ctaLabel: "Open Lovable",
    ctaHref: "https://lovable.dev",
    categories: ["Coding", "App Builder"],
    tags: ["Full‑stack", "Scaffold", "Deploy"],
    keywords: [
      "lovable",
      "loveable",
      "lovable.dev",
      "app builder",
      "generate app",
      "full stack",
      "saas starter",
      "crud",
      "auth",
      "database",
      "stripe",
      "react",
      "nextjs",
      "tailwind",
      "deploy",
      "vercel",
      "github repo",
      "code generation",
      "agent",
    ],
  },
];
